
[tool.pdm]
includes = []
build = "build_ext.py"

[tool.pdm.dev-dependencies]
dev = [
    "flake8-bugbear>=19.8.0",
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"


[project]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
name = "pya2ldb"
authors = [
    {name = "Christoph Schueler", email = "cpu12.gems@googlemail.com"},
]
requires-python = ">=3.5,<4.0"
dependencies = []
version = "0.12.62"
description = ""

[project.urls]


[project.optional-dependencies]
[tool.pytest]
addopts = "--verbose --tb=short --junitxml=result.xml -o junit_family=xunit2"
testpaths = "pya2l/tests"

[tool.flake8]
ignore = ["D203", "E203", "E266", "E501", "W503", "F403", "F401", "BLK100"]
exclude = '''
/(
    \.git
    | __pycache__
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.eggs
    | _build
    | build
    | __pypackages__
    | docs
    | dist
    | experimental
    | pya2l/a2lLexer.py
    | pya2l/amlLexer.py
    | pya2l/amlParser.py
    | pya2l/a2llg.py
    | pya2l/a2lParser.py
)/
'''
max-complexity = 10
count = true
statistics = true
show-source = true
max-line-length = 132
select = ["B","C","E","F","W","T4","B9"]

[tool.black]
line-length=132
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | __pypackages__
    | build
    | docs
    | experimental
    | __pycache__
    | pya2l/a2lLexer.py
    | pya2l/amlLexer.py
    | pya2l/amlParser.py
    | pya2l/a2llg.py
    | pya2l/a2lParser.py
    | dist
)/
'''

[tool.cibuildwheel]
build-verbosity = 3
build = "cp3{6,7,8,9,10}-*"
environment = { CLASSPATH="./antlr-4.9.3-complete.jar:" }
#test-command = "pytest {package}/tests"
#build-frontend = "build"
#build-frontend = "pip"
before-build = [
    "python install_antlr.py"
]

