[tool.poetry]
name = "pya2ldb"
version = "0.1.0"
description = ""
authors = ["Christoph Schueler <cpu12.gems@googlemail.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12", "pybind11"]
build-backend = "poetry.masonry.api"
