# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pyA2L

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
            python: ['3.5', '3.6', '3.7', '3.8', '3.9', '3.10']
    runs-on: ubuntu-latest #{{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12"
          java-package: jdk
          architecture: x64
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          wget https://www.antlr.org/download/antlr-4.9.3-complete.jar
          export CLASSPATH=".:$(pwd)/antlr-4.9.3-complete.jar:$CLASSPATH"
          python -m pip install --upgrade pip
          python -m pip install black flake8 pre-commit-hooks reorder_python_imports
          pip install -r requirements.txt
          python setup.py develop
      #- uses: pre-commit/action@v2.0.3
      - name: Test with pytest
        run: |
          export CLASSPATH=".:$(pwd)/antlr-4.9.3-complete.jar:$CLASSPATH"
          pip install -r requirements.test.txt
          pytest
      - name: Build dists
        run: |
             python setup.py bdist_wheel
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER_NAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        if: env.TWINE_USERNAME != null
        run: |
          python setup.py bdist_wheel
          twine upload dist/*
