
name: Build and distribute sdist

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools twine
        pip install -r requirements.txt
    - name: Build sdist
      run: |
          pipx run build --sdist
    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: ${{ secrets.PYPI_USER_NAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
