
name: Run tests.

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [
            #ubuntu-latest, 
            windows-latest,
            macos-latest
          ]
          python: ['3.5', '3.6', '3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -r requirements.txt
        pip install -r requirements.test.txt
        python setup.py install
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -svv
